// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ForwardRule {
  id: string
  localPort: number
  targetHost: string
  targetPort: number
  enabled: boolean
  createdAt: string
}

export interface LogEntry {
  timestamp: string
  source: string
  bytesIn: number
  bytesOut: number
  status: string
}

export function AddRule(arg1: number, arg2: string, arg3: number): Promise<void>;
export function ClearLogs(arg1: string): Promise<void>;
export function DeleteRule(arg1: string): Promise<void>;
export function GetLogs(arg1: string, arg2: number): Promise<LogEntry[]>;
export function GetRules(): Promise<ForwardRule[]>;
export function GetStatus(): Promise<{ [key: string]: boolean }>;
export function ToggleRule(arg1: string, arg2: boolean): Promise<void>;
