// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRule(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddRule'](arg1, arg2, arg3);
}

export function ClearLogs(arg1) {
  return window['go']['main']['App']['ClearLogs'](arg1);
}

export function DeleteRule(arg1) {
  return window['go']['main']['App']['DeleteRule'](arg1);
}

export function GetLogs(arg1, arg2) {
  return window['go']['main']['App']['GetLogs'](arg1, arg2);
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ToggleRule(arg1, arg2) {
  return window['go']['main']['App']['ToggleRule'](arg1, arg2);
}
